name: Zine Deploy

on:
  push:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.toml') }}
    - name: rust-cargo-install
      uses: actions-rs/install@v0.1.2
      with:
        # Binary crate name
        crate: zine
        # Store installed binary in the GitHub Actions cache (not used yet)
        use-cache: true
    - name: git-bash
      run: zine build . docs
    - name: GitHub Branch Deployer
      uses: nicholasgriffintn/github-branch-deployment-action@1.0.0
      with:
        GITHUB_TOKEN: ${{ github.token }}
        BRANCH: build
        FOLDER: docs
      
